# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TieGu/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1242, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_0 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_0.setGeometry(QtCore.QRect(70, 720, 721, 61))
        self.groupBox_0.setTitle("")
        self.groupBox_0.setObjectName("groupBox_0")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_9.setGeometry(QtCore.QRect(480, 0, 61, 41))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 0, 61, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_7.setGeometry(QtCore.QRect(360, 0, 61, 41))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_12.setGeometry(QtCore.QRect(660, 0, 61, 41))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_11.setGeometry(QtCore.QRect(600, 0, 61, 41))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 0, 61, 41))
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_10.setGeometry(QtCore.QRect(540, 0, 61, 41))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 0, 61, 41))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_8.setGeometry(QtCore.QRect(420, 0, 61, 41))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 0, 61, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 0, 61, 41))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 0, 61, 41))
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_1 = QtWidgets.QLabel(self.groupBox_0)
        self.label_1.setGeometry(QtCore.QRect(0, 40, 61, 20))
        self.label_1.setText("")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox_0)
        self.label_2.setGeometry(QtCore.QRect(61, 40, 60, 20))
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_0)
        self.label_3.setGeometry(QtCore.QRect(120, 40, 61, 20))
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_0)
        self.label_4.setGeometry(QtCore.QRect(180, 40, 60, 20))
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_0)
        self.label_5.setGeometry(QtCore.QRect(239, 40, 61, 20))
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_0)
        self.label_6.setGeometry(QtCore.QRect(300, 40, 60, 20))
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_0)
        self.label_7.setGeometry(QtCore.QRect(360, 40, 60, 20))
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_0)
        self.label_8.setGeometry(QtCore.QRect(420, 40, 60, 20))
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_0)
        self.label_9.setGeometry(QtCore.QRect(480, 40, 60, 20))
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_0)
        self.label_10.setGeometry(QtCore.QRect(540, 40, 60, 20))
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_0)
        self.label_11.setGeometry(QtCore.QRect(600, 40, 60, 20))
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_0)
        self.label_12.setGeometry(QtCore.QRect(659, 40, 61, 20))
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setEnabled(True)
        self.groupBox_1.setGeometry(QtCore.QRect(72, 410, 60, 311))
        self.groupBox_1.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(131, 410, 60, 311))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(190, 410, 61, 311))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(250, 410, 61, 311))
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(310, 410, 61, 311))
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(370, 410, 61, 311))
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(430, 410, 61, 311))
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(490, 410, 61, 311))
        self.groupBox_8.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(550, 410, 61, 311))
        self.groupBox_9.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(610, 410, 61, 311))
        self.groupBox_10.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(670, 410, 61, 311))
        self.groupBox_11.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(730, 410, 61, 311))
        self.groupBox_12.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.button_ImportJsonTalent = QtWidgets.QPushButton(self.centralwidget)
        self.button_ImportJsonTalent.setGeometry(QtCore.QRect(660, 660, 91, 31))
        self.button_ImportJsonTalent.setObjectName("button_ImportJsonTalent")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 650, 541, 61))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.skill_button_1 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_1.setGeometry(QtCore.QRect(0, 0, 60, 40))
        self.skill_button_1.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_1.setText("")
        self.skill_button_1.setObjectName("skill_button_1")
        self.skill_button_2 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_2.setGeometry(QtCore.QRect(60, 0, 60, 40))
        self.skill_button_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_2.setText("")
        self.skill_button_2.setObjectName("skill_button_2")
        self.skill_button_3 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_3.setGeometry(QtCore.QRect(120, 0, 60, 40))
        self.skill_button_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_3.setText("")
        self.skill_button_3.setObjectName("skill_button_3")
        self.skill_button_4 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_4.setGeometry(QtCore.QRect(180, 0, 60, 40))
        self.skill_button_4.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_4.setText("")
        self.skill_button_4.setObjectName("skill_button_4")
        self.skill_button_5 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_5.setGeometry(QtCore.QRect(240, 0, 60, 40))
        self.skill_button_5.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_5.setText("")
        self.skill_button_5.setObjectName("skill_button_5")
        self.skill_button_6 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_6.setGeometry(QtCore.QRect(300, 0, 60, 40))
        self.skill_button_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_6.setText("")
        self.skill_button_6.setObjectName("skill_button_6")
        self.skill_button_7 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_7.setGeometry(QtCore.QRect(360, 0, 60, 40))
        self.skill_button_7.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_7.setText("")
        self.skill_button_7.setObjectName("skill_button_7")
        self.skill_button_8 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_8.setGeometry(QtCore.QRect(420, 0, 60, 40))
        self.skill_button_8.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_8.setText("")
        self.skill_button_8.setObjectName("skill_button_8")
        self.skill_button_9 = QtWidgets.QPushButton(self.groupBox)
        self.skill_button_9.setGeometry(QtCore.QRect(480, 0, 60, 40))
        self.skill_button_9.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_skill_wide.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.skill_button_9.setText("")
        self.skill_button_9.setObjectName("skill_button_9")
        self.skill_label_1 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_1.setGeometry(QtCore.QRect(0, 40, 61, 20))
        self.skill_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_1.setObjectName("skill_label_1")
        self.skill_label_2 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_2.setGeometry(QtCore.QRect(60, 40, 61, 20))
        self.skill_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_2.setObjectName("skill_label_2")
        self.skill_label_3 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_3.setGeometry(QtCore.QRect(120, 40, 61, 20))
        self.skill_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_3.setObjectName("skill_label_3")
        self.skill_label_4 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_4.setGeometry(QtCore.QRect(180, 40, 61, 20))
        self.skill_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_4.setObjectName("skill_label_4")
        self.skill_label_5 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_5.setGeometry(QtCore.QRect(240, 40, 61, 20))
        self.skill_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_5.setObjectName("skill_label_5")
        self.skill_label_6 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_6.setGeometry(QtCore.QRect(300, 40, 61, 20))
        self.skill_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_6.setObjectName("skill_label_6")
        self.skill_label_7 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_7.setGeometry(QtCore.QRect(360, 40, 61, 20))
        self.skill_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_7.setObjectName("skill_label_7")
        self.skill_label_8 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_8.setGeometry(QtCore.QRect(420, 40, 61, 20))
        self.skill_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_8.setObjectName("skill_label_8")
        self.skill_label_9 = QtWidgets.QLabel(self.groupBox)
        self.skill_label_9.setGeometry(QtCore.QRect(480, 40, 61, 20))
        self.skill_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.skill_label_9.setObjectName("skill_label_9")
        self.groupBox_skill_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_1.setGeometry(QtCore.QRect(10, 360, 181, 291))
        self.groupBox_skill_1.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_1.setTitle("")
        self.groupBox_skill_1.setObjectName("groupBox_skill_1")
        self.pushButton_79 = QtWidgets.QPushButton(self.groupBox_skill_1)
        self.pushButton_79.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_79.setStyleSheet("")
        self.pushButton_79.setObjectName("pushButton_79")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_skill_1)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_skill_1)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_13 = QtWidgets.QLabel(self.groupBox_skill_1)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_skill_1)
        self.label_14.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_skill_1)
        self.pushButton_15.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_skill_1)
        self.pushButton_16.setGeometry(QtCore.QRect(120, 30, 40, 40))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_skill_1)
        self.pushButton_17.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_skill_1)
        self.pushButton_18.setGeometry(QtCore.QRect(120, 100, 40, 40))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label = QtWidgets.QLabel(self.groupBox_skill_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.groupBox_skill_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_2.setGeometry(QtCore.QRect(70, 360, 181, 291))
        self.groupBox_skill_2.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_2.setTitle("")
        self.groupBox_skill_2.setObjectName("groupBox_skill_2")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_skill_2)
        self.pushButton_19.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_skill_2)
        self.pushButton_20.setGeometry(QtCore.QRect(20, 240, 40, 40))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_15 = QtWidgets.QLabel(self.groupBox_skill_2)
        self.label_15.setGeometry(QtCore.QRect(10, 220, 161, 16))
        self.label_15.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_skill_2)
        self.label_16.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_16.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_skill_2)
        self.pushButton_22.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_skill_2)
        self.pushButton_23.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_23.setObjectName("pushButton_23")
        self.label_17 = QtWidgets.QLabel(self.groupBox_skill_2)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_17.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_skill_2)
        self.pushButton_25.setGeometry(QtCore.QRect(70, 170, 40, 40))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_skill_2)
        self.pushButton_21.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_18 = QtWidgets.QLabel(self.groupBox_skill_2)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_18.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_skill_2)
        self.pushButton_24.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_24.setStyleSheet("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_skill_2)
        self.pushButton_26.setGeometry(QtCore.QRect(70, 240, 40, 40))
        self.pushButton_26.setObjectName("pushButton_26")
        self.groupBox_skill_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_3.setGeometry(QtCore.QRect(130, 360, 181, 291))
        self.groupBox_skill_3.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_3.setTitle("")
        self.groupBox_skill_3.setObjectName("groupBox_skill_3")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_skill_3)
        self.pushButton_27.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.groupBox_skill_3)
        self.pushButton_28.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_skill_3)
        self.pushButton_29.setGeometry(QtCore.QRect(120, 100, 40, 40))
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_19 = QtWidgets.QLabel(self.groupBox_skill_3)
        self.label_19.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_19.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_skill_3)
        self.label_20.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_20.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_skill_3)
        self.pushButton_30.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_30.setStyleSheet("")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_skill_3)
        self.pushButton_31.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_31.setObjectName("pushButton_31")
        self.label_21 = QtWidgets.QLabel(self.groupBox_skill_3)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_21.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_21.setObjectName("label_21")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_skill_3)
        self.pushButton_32.setGeometry(QtCore.QRect(120, 30, 40, 40))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox_skill_3)
        self.pushButton_33.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_33.setObjectName("pushButton_33")
        self.groupBox_skill_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_4.setGeometry(QtCore.QRect(190, 360, 181, 291))
        self.groupBox_skill_4.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_4.setTitle("")
        self.groupBox_skill_4.setObjectName("groupBox_skill_4")
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox_skill_4)
        self.pushButton_34.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox_skill_4)
        self.pushButton_35.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.groupBox_skill_4)
        self.pushButton_36.setGeometry(QtCore.QRect(120, 100, 40, 40))
        self.pushButton_36.setObjectName("pushButton_36")
        self.label_22 = QtWidgets.QLabel(self.groupBox_skill_4)
        self.label_22.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_22.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_skill_4)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_23.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox_skill_4)
        self.pushButton_37.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_37.setStyleSheet("")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox_skill_4)
        self.pushButton_38.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_38.setObjectName("pushButton_38")
        self.label_24 = QtWidgets.QLabel(self.groupBox_skill_4)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_24.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_skill_4)
        self.pushButton_39.setGeometry(QtCore.QRect(120, 30, 40, 40))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_skill_4)
        self.pushButton_40.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_skill_4)
        self.pushButton_41.setGeometry(QtCore.QRect(70, 170, 40, 40))
        self.pushButton_41.setObjectName("pushButton_41")
        self.groupBox_skill_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_5.setGeometry(QtCore.QRect(250, 360, 181, 291))
        self.groupBox_skill_5.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_5.setTitle("")
        self.groupBox_skill_5.setObjectName("groupBox_skill_5")
        self.label_25 = QtWidgets.QLabel(self.groupBox_skill_5)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_skill_5)
        self.label_26.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_26.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox_skill_5)
        self.pushButton_42.setGeometry(QtCore.QRect(20, 240, 40, 40))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_skill_5)
        self.pushButton_44.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_44.setStyleSheet("")
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.groupBox_skill_5)
        self.pushButton_45.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(self.groupBox_skill_5)
        self.pushButton_46.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(self.groupBox_skill_5)
        self.pushButton_47.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_47.setObjectName("pushButton_47")
        self.label_27 = QtWidgets.QLabel(self.groupBox_skill_5)
        self.label_27.setGeometry(QtCore.QRect(10, 220, 161, 16))
        self.label_27.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.pushButton_48 = QtWidgets.QPushButton(self.groupBox_skill_5)
        self.pushButton_48.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self.groupBox_skill_5)
        self.pushButton_49.setGeometry(QtCore.QRect(70, 170, 40, 40))
        self.pushButton_49.setObjectName("pushButton_49")
        self.label_28 = QtWidgets.QLabel(self.groupBox_skill_5)
        self.label_28.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_28.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_28.setObjectName("label_28")
        self.groupBox_skill_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_6.setGeometry(QtCore.QRect(310, 360, 181, 291))
        self.groupBox_skill_6.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_6.setTitle("")
        self.groupBox_skill_6.setObjectName("groupBox_skill_6")
        self.pushButton_52 = QtWidgets.QPushButton(self.groupBox_skill_6)
        self.pushButton_52.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_52.setStyleSheet("")
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(self.groupBox_skill_6)
        self.pushButton_53.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(self.groupBox_skill_6)
        self.pushButton_54.setGeometry(QtCore.QRect(70, 170, 40, 40))
        self.pushButton_54.setObjectName("pushButton_54")
        self.label_29 = QtWidgets.QLabel(self.groupBox_skill_6)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_29.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_29.setObjectName("label_29")
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_skill_6)
        self.pushButton_43.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_43.setObjectName("pushButton_43")
        self.label_31 = QtWidgets.QLabel(self.groupBox_skill_6)
        self.label_31.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_31.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_31.setObjectName("label_31")
        self.label_30 = QtWidgets.QLabel(self.groupBox_skill_6)
        self.label_30.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_30.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_30.setObjectName("label_30")
        self.pushButton_50 = QtWidgets.QPushButton(self.groupBox_skill_6)
        self.pushButton_50.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_50.setStyleSheet("")
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(self.groupBox_skill_6)
        self.pushButton_51.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_51.setObjectName("pushButton_51")
        self.groupBox_skill_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_7.setGeometry(QtCore.QRect(370, 360, 181, 291))
        self.groupBox_skill_7.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_7.setTitle("")
        self.groupBox_skill_7.setObjectName("groupBox_skill_7")
        self.pushButton_55 = QtWidgets.QPushButton(self.groupBox_skill_7)
        self.pushButton_55.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_55.setStyleSheet("")
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(self.groupBox_skill_7)
        self.pushButton_56.setGeometry(QtCore.QRect(20, 240, 40, 40))
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(self.groupBox_skill_7)
        self.pushButton_57.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(self.groupBox_skill_7)
        self.pushButton_58.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(self.groupBox_skill_7)
        self.pushButton_59.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_59.setObjectName("pushButton_59")
        self.label_32 = QtWidgets.QLabel(self.groupBox_skill_7)
        self.label_32.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_32.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_32.setObjectName("label_32")
        self.pushButton_60 = QtWidgets.QPushButton(self.groupBox_skill_7)
        self.pushButton_60.setGeometry(QtCore.QRect(70, 170, 40, 40))
        self.pushButton_60.setObjectName("pushButton_60")
        self.label_33 = QtWidgets.QLabel(self.groupBox_skill_7)
        self.label_33.setGeometry(QtCore.QRect(10, 220, 161, 16))
        self.label_33.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.groupBox_skill_7)
        self.label_34.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_34.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_34.setObjectName("label_34")
        self.pushButton_61 = QtWidgets.QPushButton(self.groupBox_skill_7)
        self.pushButton_61.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_61.setStyleSheet("")
        self.pushButton_61.setObjectName("pushButton_61")
        self.label_35 = QtWidgets.QLabel(self.groupBox_skill_7)
        self.label_35.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_35.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_35.setObjectName("label_35")
        self.pushButton_62 = QtWidgets.QPushButton(self.groupBox_skill_7)
        self.pushButton_62.setGeometry(QtCore.QRect(70, 240, 40, 40))
        self.pushButton_62.setObjectName("pushButton_62")
        self.groupBox_skill_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_8.setGeometry(QtCore.QRect(430, 360, 181, 291))
        self.groupBox_skill_8.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_8.setTitle("")
        self.groupBox_skill_8.setObjectName("groupBox_skill_8")
        self.pushButton_69 = QtWidgets.QPushButton(self.groupBox_skill_8)
        self.pushButton_69.setGeometry(QtCore.QRect(120, 30, 40, 40))
        self.pushButton_69.setStyleSheet("")
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_70 = QtWidgets.QPushButton(self.groupBox_skill_8)
        self.pushButton_70.setGeometry(QtCore.QRect(120, 100, 40, 40))
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_64 = QtWidgets.QPushButton(self.groupBox_skill_8)
        self.pushButton_64.setGeometry(QtCore.QRect(70, 170, 40, 40))
        self.pushButton_64.setObjectName("pushButton_64")
        self.label_38 = QtWidgets.QLabel(self.groupBox_skill_8)
        self.label_38.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_38.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_38.setObjectName("label_38")
        self.label_37 = QtWidgets.QLabel(self.groupBox_skill_8)
        self.label_37.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_37.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_37.setObjectName("label_37")
        self.pushButton_67 = QtWidgets.QPushButton(self.groupBox_skill_8)
        self.pushButton_67.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_67.setStyleSheet("")
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_63 = QtWidgets.QPushButton(self.groupBox_skill_8)
        self.pushButton_63.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_63.setObjectName("pushButton_63")
        self.label_36 = QtWidgets.QLabel(self.groupBox_skill_8)
        self.label_36.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_36.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_36.setObjectName("label_36")
        self.pushButton_68 = QtWidgets.QPushButton(self.groupBox_skill_8)
        self.pushButton_68.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_66 = QtWidgets.QPushButton(self.groupBox_skill_8)
        self.pushButton_66.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_65 = QtWidgets.QPushButton(self.groupBox_skill_8)
        self.pushButton_65.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_65.setStyleSheet("")
        self.pushButton_65.setObjectName("pushButton_65")
        self.groupBox_skill_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_skill_9.setGeometry(QtCore.QRect(490, 360, 181, 291))
        self.groupBox_skill_9.setStyleSheet("QGroupBox{\n"
"    border-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"    background-color: rgb(222, 211, 211)\n"
"}")
        self.groupBox_skill_9.setTitle("")
        self.groupBox_skill_9.setObjectName("groupBox_skill_9")
        self.pushButton_78 = QtWidgets.QPushButton(self.groupBox_skill_9)
        self.pushButton_78.setGeometry(QtCore.QRect(120, 100, 40, 40))
        self.pushButton_78.setObjectName("pushButton_78")
        self.pushButton_74 = QtWidgets.QPushButton(self.groupBox_skill_9)
        self.pushButton_74.setGeometry(QtCore.QRect(20, 100, 40, 40))
        self.pushButton_74.setObjectName("pushButton_74")
        self.pushButton_76 = QtWidgets.QPushButton(self.groupBox_skill_9)
        self.pushButton_76.setGeometry(QtCore.QRect(20, 170, 40, 40))
        self.pushButton_76.setObjectName("pushButton_76")
        self.pushButton_77 = QtWidgets.QPushButton(self.groupBox_skill_9)
        self.pushButton_77.setGeometry(QtCore.QRect(70, 30, 40, 40))
        self.pushButton_77.setStyleSheet("")
        self.pushButton_77.setObjectName("pushButton_77")
        self.pushButton_73 = QtWidgets.QPushButton(self.groupBox_skill_9)
        self.pushButton_73.setGeometry(QtCore.QRect(70, 100, 40, 40))
        self.pushButton_73.setObjectName("pushButton_73")
        self.pushButton_75 = QtWidgets.QPushButton(self.groupBox_skill_9)
        self.pushButton_75.setGeometry(QtCore.QRect(120, 30, 40, 40))
        self.pushButton_75.setStyleSheet("")
        self.pushButton_75.setObjectName("pushButton_75")
        self.label_40 = QtWidgets.QLabel(self.groupBox_skill_9)
        self.label_40.setGeometry(QtCore.QRect(10, 150, 161, 16))
        self.label_40.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_40.setObjectName("label_40")
        self.pushButton_71 = QtWidgets.QPushButton(self.groupBox_skill_9)
        self.pushButton_71.setGeometry(QtCore.QRect(20, 30, 40, 40))
        self.pushButton_71.setStyleSheet("")
        self.pushButton_71.setObjectName("pushButton_71")
        self.label_41 = QtWidgets.QLabel(self.groupBox_skill_9)
        self.label_41.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_41.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_41.setObjectName("label_41")
        self.label_39 = QtWidgets.QLabel(self.groupBox_skill_9)
        self.label_39.setGeometry(QtCore.QRect(10, 80, 161, 16))
        self.label_39.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(65, 54, 100, 255), stop:0.744318 rgba(222, 211, 211, 255));\n"
"color: rgb(255, 255, 255);")
        self.label_39.setObjectName("label_39")
        self.pushButton_72 = QtWidgets.QPushButton(self.groupBox_skill_9)
        self.pushButton_72.setGeometry(QtCore.QRect(70, 170, 40, 40))
        self.pushButton_72.setObjectName("pushButton_72")
        self.button_main = QtWidgets.QPushButton(self.centralwidget)
        self.button_main.setGeometry(QtCore.QRect(70, 110, 91, 31))
        self.button_main.setObjectName("button_main")
        self.button_tocsv = QtWidgets.QPushButton(self.centralwidget)
        self.button_tocsv.setGeometry(QtCore.QRect(70, 160, 91, 31))
        self.button_tocsv.setObjectName("button_tocsv")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(870, 770, 331, 20))
        self.label_info.setText("")
        self.label_info.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_info.setObjectName("label_info")
        self.Level_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.Level_spinBox.setGeometry(QtCore.QRect(130, 50, 51, 22))
        self.Level_spinBox.setMinimum(120)
        self.Level_spinBox.setMaximum(124)
        self.Level_spinBox.setProperty("value", 124)
        self.Level_spinBox.setObjectName("Level_spinBox")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(70, 51, 54, 21))
        self.label_42.setObjectName("label_42")
        self.skill_data_table = QtWidgets.QTableWidget(self.centralwidget)
        self.skill_data_table.setGeometry(QtCore.QRect(820, 340, 404, 421))
        self.skill_data_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.skill_data_table.setObjectName("skill_data_table")
        self.skill_data_table.setColumnCount(5)
        self.skill_data_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.skill_data_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.skill_data_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.skill_data_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.skill_data_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.skill_data_table.setHorizontalHeaderItem(4, item)
        self.skill_data_table.horizontalHeader().setDefaultSectionSize(76)
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(820, 310, 71, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.dps_label = QtWidgets.QLabel(self.centralwidget)
        self.dps_label.setGeometry(QtCore.QRect(860, 310, 91, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.dps_label.setFont(font)
        self.dps_label.setText("")
        self.dps_label.setObjectName("dps_label")
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(70, 210, 721, 411))
        self.groupBox_13.setObjectName("groupBox_13")
        self.qijin_checkBox = QtWidgets.QCheckBox(self.groupBox_13)
        self.qijin_checkBox.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.qijin_checkBox.setObjectName("qijin_checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1242, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "苍云模拟器"))
        self.button_ImportJsonTalent.setText(_translate("MainWindow", "导入奇穴编码"))
        self.skill_label_1.setText(_translate("MainWindow", "盾刀"))
        self.skill_label_2.setText(_translate("MainWindow", "盾压"))
        self.skill_label_3.setText(_translate("MainWindow", "劫刀"))
        self.skill_label_4.setText(_translate("MainWindow", "斩刀"))
        self.skill_label_5.setText(_translate("MainWindow", "绝刀"))
        self.skill_label_6.setText(_translate("MainWindow", "盾飞"))
        self.skill_label_7.setText(_translate("MainWindow", "盾舞"))
        self.skill_label_8.setText(_translate("MainWindow", "盾墙"))
        self.skill_label_9.setText(_translate("MainWindow", "血怒"))
        self.pushButton_79.setText(_translate("MainWindow", "+2%"))
        self.pushButton_13.setText(_translate("MainWindow", "+3%"))
        self.pushButton_14.setText(_translate("MainWindow", "+5怒"))
        self.label_13.setText(_translate("MainWindow", " 招式伤害"))
        self.label_14.setText(_translate("MainWindow", " 招式效果"))
        self.pushButton_15.setText(_translate("MainWindow", "+3%"))
        self.pushButton_16.setText(_translate("MainWindow", "+4%"))
        self.pushButton_17.setText(_translate("MainWindow", "+4%"))
        self.pushButton_18.setText(_translate("MainWindow", "+5%"))
        self.label.setText(_translate("MainWindow", " 会心几率"))
        self.pushButton_19.setText(_translate("MainWindow", "+4%"))
        self.pushButton_20.setText(_translate("MainWindow", "+5%"))
        self.label_15.setText(_translate("MainWindow", " 招式效果"))
        self.label_16.setText(_translate("MainWindow", " 招式伤害"))
        self.pushButton_22.setText(_translate("MainWindow", "+3%"))
        self.pushButton_23.setText(_translate("MainWindow", "+4%"))
        self.label_17.setText(_translate("MainWindow", " 会心几率"))
        self.pushButton_25.setText(_translate("MainWindow", "+5%"))
        self.pushButton_21.setText(_translate("MainWindow", "-1秒"))
        self.label_18.setText(_translate("MainWindow", " 调息时间"))
        self.pushButton_24.setText(_translate("MainWindow", "-1秒"))
        self.pushButton_26.setText(_translate("MainWindow", "+5%"))
        self.pushButton_27.setText(_translate("MainWindow", "+3%"))
        self.pushButton_28.setText(_translate("MainWindow", "-5怒"))
        self.pushButton_29.setText(_translate("MainWindow", "+5%"))
        self.label_19.setText(_translate("MainWindow", " 招式消耗"))
        self.label_20.setText(_translate("MainWindow", " 招式伤害"))
        self.pushButton_30.setText(_translate("MainWindow", "+2%"))
        self.pushButton_31.setText(_translate("MainWindow", "+3%"))
        self.label_21.setText(_translate("MainWindow", " 会心几率"))
        self.pushButton_32.setText(_translate("MainWindow", "+4%"))
        self.pushButton_33.setText(_translate("MainWindow", "+4%"))
        self.pushButton_34.setText(_translate("MainWindow", "+3%"))
        self.pushButton_35.setText(_translate("MainWindow", "锁足"))
        self.pushButton_36.setText(_translate("MainWindow", "+5%"))
        self.label_22.setText(_translate("MainWindow", " 招式效果"))
        self.label_23.setText(_translate("MainWindow", " 招式伤害"))
        self.pushButton_37.setText(_translate("MainWindow", "+2%"))
        self.pushButton_38.setText(_translate("MainWindow", "+3%"))
        self.label_24.setText(_translate("MainWindow", " 会心几率"))
        self.pushButton_39.setText(_translate("MainWindow", "+4%"))
        self.pushButton_40.setText(_translate("MainWindow", "+4%"))
        self.pushButton_41.setText(_translate("MainWindow", "解控"))
        self.label_25.setText(_translate("MainWindow", " 会心几率"))
        self.label_26.setText(_translate("MainWindow", " 招式伤害"))
        self.pushButton_42.setText(_translate("MainWindow", "-15怒"))
        self.pushButton_44.setText(_translate("MainWindow", "+3%"))
        self.pushButton_45.setText(_translate("MainWindow", "+4%"))
        self.pushButton_46.setText(_translate("MainWindow", "+5%"))
        self.pushButton_47.setText(_translate("MainWindow", "+4%"))
        self.label_27.setText(_translate("MainWindow", " 招式效果"))
        self.pushButton_48.setText(_translate("MainWindow", "-1秒"))
        self.pushButton_49.setText(_translate("MainWindow", "-2秒"))
        self.label_28.setText(_translate("MainWindow", " 调息时间"))
        self.pushButton_52.setText(_translate("MainWindow", "+3%"))
        self.pushButton_53.setText(_translate("MainWindow", "+4%"))
        self.pushButton_54.setText(_translate("MainWindow", "+5秒"))
        self.label_29.setText(_translate("MainWindow", " 会心几率"))
        self.pushButton_43.setText(_translate("MainWindow", "+5秒"))
        self.label_31.setText(_translate("MainWindow", " 效果持续时间"))
        self.label_30.setText(_translate("MainWindow", " 招式伤害"))
        self.pushButton_50.setText(_translate("MainWindow", "+2%"))
        self.pushButton_51.setText(_translate("MainWindow", "+3%"))
        self.pushButton_55.setText(_translate("MainWindow", "+3%"))
        self.pushButton_56.setText(_translate("MainWindow", "+1秒"))
        self.pushButton_57.setText(_translate("MainWindow", "+4%"))
        self.pushButton_58.setText(_translate("MainWindow", "+4%"))
        self.pushButton_59.setText(_translate("MainWindow", "+5%"))
        self.label_32.setText(_translate("MainWindow", " 招式伤害"))
        self.pushButton_60.setText(_translate("MainWindow", "+1尺"))
        self.label_33.setText(_translate("MainWindow", " 招式效果"))
        self.label_34.setText(_translate("MainWindow", " 会心几率"))
        self.pushButton_61.setText(_translate("MainWindow", "+1尺"))
        self.label_35.setText(_translate("MainWindow", " 招式施展范围"))
        self.pushButton_62.setText(_translate("MainWindow", "+2秒"))
        self.pushButton_69.setText(_translate("MainWindow", "-5秒"))
        self.pushButton_70.setText(_translate("MainWindow", "+5%"))
        self.pushButton_64.setText(_translate("MainWindow", "-10%"))
        self.label_38.setText(_translate("MainWindow", " 招式效果"))
        self.label_37.setText(_translate("MainWindow", " 招式效果"))
        self.pushButton_67.setText(_translate("MainWindow", "-5秒"))
        self.pushButton_63.setText(_translate("MainWindow", "+5%"))
        self.label_36.setText(_translate("MainWindow", " 调息时间"))
        self.pushButton_68.setText(_translate("MainWindow", "+5%"))
        self.pushButton_66.setText(_translate("MainWindow", "-10%"))
        self.pushButton_65.setText(_translate("MainWindow", "-5秒"))
        self.pushButton_78.setText(_translate("MainWindow", "+1秒"))
        self.pushButton_74.setText(_translate("MainWindow", "+1秒"))
        self.pushButton_76.setText(_translate("MainWindow", "+2%"))
        self.pushButton_77.setText(_translate("MainWindow", "+5怒"))
        self.pushButton_73.setText(_translate("MainWindow", "+1秒"))
        self.pushButton_75.setText(_translate("MainWindow", "+5怒"))
        self.label_40.setText(_translate("MainWindow", " 招式效果"))
        self.pushButton_71.setText(_translate("MainWindow", "+5怒"))
        self.label_41.setText(_translate("MainWindow", " 招式效果"))
        self.label_39.setText(_translate("MainWindow", " 效果持续时间"))
        self.pushButton_72.setText(_translate("MainWindow", "+3%"))
        self.button_main.setText(_translate("MainWindow", "开始模拟"))
        self.button_tocsv.setText(_translate("MainWindow", "导出csv"))
        self.label_42.setText(_translate("MainWindow", "首领等级"))
        item = self.skill_data_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "技能名"))
        item = self.skill_data_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "数量"))
        item = self.skill_data_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "总伤害"))
        item = self.skill_data_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "占比"))
        item = self.skill_data_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "会心率"))
        self.label_43.setText(_translate("MainWindow", "DPS："))
        self.groupBox_13.setTitle(_translate("MainWindow", "设置"))
        self.qijin_checkBox.setText(_translate("MainWindow", "铁骨气劲"))
import ui_rc
