# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '铁骨循环模拟器/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1242, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, -110, 521, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_0 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_0.setGeometry(QtCore.QRect(50, 720, 721, 61))
        self.groupBox_0.setTitle("")
        self.groupBox_0.setObjectName("groupBox_0")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_9.setGeometry(QtCore.QRect(490, 0, 41, 41))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 0, 41, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 0, 41, 41))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_12.setGeometry(QtCore.QRect(670, 0, 41, 41))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_11.setGeometry(QtCore.QRect(610, 0, 41, 41))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 0, 41, 41))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_10.setGeometry(QtCore.QRect(550, 0, 41, 41))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_6.setGeometry(QtCore.QRect(310, 0, 41, 41))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_8.setGeometry(QtCore.QRect(430, 0, 41, 41))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 0, 41, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_0)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 0, 41, 41))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.PushButton_1 = QtWidgets.QPushButton(self.groupBox_0)
        self.PushButton_1.setGeometry(QtCore.QRect(10, 0, 41, 41))
        self.PushButton_1.setStyleSheet("QPushButton{\n"
"background-image: url(:/main/source/border_qx.png);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 193, 130);\n"
"}")
        self.PushButton_1.setText("")
        self.PushButton_1.setObjectName("PushButton_1")
        self.label_1 = QtWidgets.QLabel(self.groupBox_0)
        self.label_1.setGeometry(QtCore.QRect(0, 40, 61, 20))
        self.label_1.setText("")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.groupBox_0)
        self.label_2.setGeometry(QtCore.QRect(61, 40, 60, 20))
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_0)
        self.label_3.setGeometry(QtCore.QRect(120, 40, 61, 20))
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_0)
        self.label_4.setGeometry(QtCore.QRect(180, 40, 60, 20))
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_0)
        self.label_5.setGeometry(QtCore.QRect(239, 40, 61, 20))
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_0)
        self.label_6.setGeometry(QtCore.QRect(300, 40, 60, 20))
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_0)
        self.label_7.setGeometry(QtCore.QRect(360, 40, 60, 20))
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_0)
        self.label_8.setGeometry(QtCore.QRect(420, 40, 60, 20))
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_0)
        self.label_9.setGeometry(QtCore.QRect(480, 40, 60, 20))
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_0)
        self.label_10.setGeometry(QtCore.QRect(540, 40, 60, 20))
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_0)
        self.label_11.setGeometry(QtCore.QRect(600, 40, 60, 20))
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_0)
        self.label_12.setGeometry(QtCore.QRect(659, 40, 61, 20))
        self.label_12.setText("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(52, 410, 60, 311))
        self.groupBox_1.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(111, 410, 60, 311))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(170, 410, 61, 311))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 410, 61, 311))
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 410, 61, 311))
        self.groupBox_5.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(350, 410, 61, 311))
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(410, 410, 61, 311))
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(470, 410, 61, 311))
        self.groupBox_8.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(530, 410, 61, 311))
        self.groupBox_9.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(590, 410, 61, 311))
        self.groupBox_10.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(650, 410, 61, 311))
        self.groupBox_11.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(710, 410, 61, 311))
        self.groupBox_12.setStyleSheet("QGroupBox{\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    border-color: rgb(65, 54, 100);\n"
"    border: 2px solid;\n"
"}")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1242, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "苍云模拟器"))
import ui_rc
